import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const webDir = path.join(here, '..', 'web');
const outFile = path.join(here, '..', 'src', 'assets.generated.js');

const names = ['index.html', 'app.js', 'styles.css'];
const entries = names.map((name) => {
  const body = fs.readFileSync(path.join(webDir, name), 'utf8');
  return '  ' + JSON.stringify(name) + ': ' + JSON.stringify(body);
});

const source = [
  '// GENERATED by scripts/genassets.mjs - do not edit.',
  '// The dashboard assets, embedded so the packaged executable has no side files.',
  'export const ASSETS = {',
  entries.join(',\n'),
  '};',
  ''
].join('\n');

fs.writeFileSync(outFile, source);
console.log('[genassets] embedded ' + names.length + ' assets (' + source.length + ' bytes)');
